defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

excerpt_separator: <!--mehr-->

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
title: benoegen - locker flockig
tagline: ein blog mit blick auf die eigenen fotos und videos aus dem ganzen web
url: http://benoegen.de
author: benoegen
